apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: grade-submission
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Mihailo222/ArgoCD.git
    targetRevision: HEAD
    path: argo_deployments
  destination: 
    server: https://kubernetes.default.svc
    namespace: grade-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    sycOptions:
      - CreateNamespace=true
