# custom helm chart values

customIngressResource:
  enabled: true
  ingressClassName: nginx
  host: grafana.local
  grafanaPath: "/grafana"

  service:
    name: prom-grafana-application
    port: 80
    servicenamespace: prometheus-grafana

grafana:
  grafana.ini:
    server:
      root_url: http://grafana.local/grafana/
      serve_from_sub_path: true

    database:
      wal: true
      cache_mode: shared
